#!/bin/bash

#set -e

#apt-get update >/dev/null 2>&1 || apt-get install bc >/dev/null 2>&1
#apt-get install bc >/dev/null 2>&1

if [ "$1" = "" ]
  then
    printf "Warning: No arguments supplied\n"
    exit
fi

VIDEO='./Example/submit_correct.mp4'
#VIDEO='./Example/Train.avi'
#VIDEO='./Example/Train1.avi'
echo $VIDEO
# Set frames constant for test video
FRAMES=1000.0

# Space for new command
SPACE=' '

# Make run command
RUN_CMD=$1$SPACE$VIDEO

# Set clock
start_time=$(date +'%s')
echo $RUN_CMD

# Run suppiled function with image argument
# Outputs pixel labeled array
# Stored for comparison
$RUN_CMD > tester_data

# Output runtime
end_time=$(date +'%s')

printf "\nYour program has been ran, now grading...\n"
FPS=$(echo "scale=3; $FRAMES/($end_time - $start_time)" | bc)

CODE_CMD='python3 Example/score_grader'
TMP_LOCATION='tester_data'

PYTHON_CMD=$CODE_CMD$SPACE$TMP_LOCATION$SPACE$FPS$SPACE$input_user

echo $PYTHON_CMD

# Run python program to calculate accuracy and store info for database
ACC=$($PYTHON_CMD 2>&1)

printf "\nYour program runs at $FPS FPS\n\n"

echo $ACC
echo ' '
exit
#rm tester_data >/dev/null 2>&1
rm Example/image.png >/dev/null 2>&1
